Repository dietza/rowdy-taters, pull requests merged in 2021-02, with the labels that each got.

#2 Ad/architecture
  .eslintcache
  public/index.html
  src/App.js
  src/Components/App/App-test.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Details/Details-test.js
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/MovieCard/MovieCard-test.js
  src/Components/MovieCard/MovieCard.css
  src/Components/MovieCard/MovieCard.js
  src/Components/Movies/Movies-test.js
  src/Components/Movies/Movies.css
  src/Components/Movies/Movies.js
  src/index.js
Labels: documentation, set-up

#16 Ad/feature/details view
  .eslintcache
  .gitignore
  src/Components/App/App.js
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/Details/double-left-arrows.svg
  src/Components/Header/Header.css
  src/Components/MovieCard/MovieCard.js
  src/Components/Movies/Movies.js
  src/movieData.js
Labels: App Component, Details Component, enhancement

#17 Kb/feature/access api data
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/Details/Details.js
  src/Components/DetailsDisplay/DetailsDisplay-test.js
  src/Components/DetailsDisplay/DetailsDisplay.css
  src/Components/DetailsDisplay/DetailsDisplay.js
  src/apiCalls.js
Labels: App Component, Details Component, Fetch-API, Movies Component

#18 Ad/feature/router setup
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/Details/Details.js
  src/Components/Movies/Movies.js
  src/index.js
Labels: App Component, Router

#19 Ad/cypress testing setup
  .eslintcache
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/moneyPlaneMockData.json
  cypress/fixtures/peninsulaMockData.json
  cypress/integration/details_spec.js
  cypress/integration/rowdy_taters_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/Details/Details.js
  src/Components/DetailsDisplay/DetailsDisplay.js
Labels: Fetch-API, documentation, testing

#20 Kb/feature/prop types
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/Details/Details.js
  src/Components/DetailsDisplay/DetailsDisplay.js
  src/Components/MovieCard/MovieCard.js
  src/Components/Movies/Movies.js
Labels: Details Component, MovieCard Component, Movies Component

#24 Kb/feature/about page
  src/AD.jpg
  src/Components/About/About.css
  src/Components/About/About.js
  src/Components/App/App.js
  src/Components/Contact/Contact.css
  src/Components/Contact/Contact.js
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/Movies/Movies.css
  src/KB1.jpg
  src/double-left-arrows.svg
  src/tater_tot.jpg
Labels: AboutPage Component, ContactUs Component, Router, styling

#27 Ad/feature/search bar
  src/Components/App/App.js
  src/Components/Details/Details.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Movies/Movies.js
  src/Components/SearchBar/SearchBar.css
  src/Components/SearchBar/SearchBar.js
Labels: Header Component, SearchBar Component, enhancement, styling

#28 Kb/fix/css polish
  public/favicon.ico
  src/Components/App/App.js
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/DetailsDisplay/DetailsDisplay.js
  src/Components/Footer/Footer.css
  src/Components/Header/Header.css
  src/Components/MovieCard/MovieCard.css
  src/Components/Movies/Movies.css
  src/Components/SearchBar/SearchBar.css
  src/rowdytater1.png
Labels: styling

#34 Ad/feature/testing expansion
  cypress/integration/about_spec.js
  cypress/integration/contact_spec.js
  cypress/integration/details_spec.js
  cypress/integration/rowdy_taters_spec.js
  src/Components/App/App.js
  src/Components/Contact/Contact.js
  src/Components/Details/Details.js
  src/Components/Footer/Footer.js
  src/Components/Movies/Movies.js
Labels: AboutPage Component, ContactUs Component, SearchBar Component, documentation, testing

#35 Kb/fix/file cleanup
  cypress/fixtures/example.json
  src/Components/About/About.css
  src/Components/About/About.js
  src/Components/App/App-test.js
  src/Components/App/App.js
  src/Components/Contact/Contact.css
  src/Components/Contact/Contact.js
  src/Components/Details/Details-test.js
  src/Components/Details/Details.js
  src/Components/DetailsDisplay/DetailsDisplay-test.js
  src/Components/Footer/Footer.js
  src/Components/Header/Header-test.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/MovieCard/MovieCard-test.js
  src/Components/MovieCard/MovieCard.css
  src/Components/MovieCard/MovieCard.js
  src/Components/Movies/Movies-test.js
  src/Components/Movies/Movies.js
  src/Components/SearchBar/SearchBar.js
  src/assets/AD.jpg
  src/assets/KB1.jpg
  src/assets/double-left-arrows.svg
  src/assets/rowdytater1.png
  src/assets/tater_tot.jpg
  src/index.js
  src/movieData.js
  src/setupTests.js
Labels: refactor

#36 Ad/refactor/css cleanup
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Details/Details.css
  src/Components/DetailsDisplay/DetailsDisplay.css
  src/Components/DetailsDisplay/DetailsDisplay.js
  src/Components/Footer/Footer.css
  src/Components/Header/Header.css
  src/Components/MovieCard/MovieCard.css
  src/Components/Movies/Movies.css
  src/index.css
Labels: refactor, styling

#37 Kb/fix/error handling
  cypress/integration/about_spec.js
  cypress/integration/contact_spec.js
  cypress/integration/details_spec.js
  cypress/integration/rowdy_taters_spec.js
  src/Components/App/App.js
  src/Components/Details/Details.js
  src/Components/DetailsDisplay/DetailsDisplay.js
Labels: refactor, styling, testing

#38 Ad/refactor/accessibility
  src/Components/About/About.js
  src/Components/Contact/Contact.js
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/MovieCard/MovieCard.js
  src/Components/SearchBar/SearchBar.js
Labels: accessibility, refactor

#39 Refactor/update readme
  README.md
Labels: documentation
